// Generated by CoffeeScript 1.12.5
(function() {
  var auswerte, checkAntwort, fBeantwortet, fNr, frage, loesungS, neueFrage, richtige,
      audio;

  fNr = 0;

  frage = null;

  fBeantwortet = true;

  loesungS = "";

  richtige = 0;

  auswerte = function() {
    $("#btnAntwort").hide();
    return $("#Antworten").hide();
  };

  checkAntwort = function() {
    var aIdx, lastFrage;
    aIdx = parseInt($("input[name='Antwort']:checked").val());
    lastFrage = quiz.Fragen.length === fNr + 1;
    preLastFrage = quiz.Fragen.length === fNr + 2;
    $("#btnAntwort").html("Weiter zu Frage " + (fNr + 2));
    $("#Antworten").hide();
    if (frage.Loesung === aIdx - 1) {
      loesungS += frage.Letter;
      richtige++;
      $('h3').html("Richtig!");
      $(imgTrue).show();
    } else {
      loesungS += '?';
      $('h3').html("Falsch!");
      $(imgFalse).show();
    }
    if (preLastFrage) {
      if (richtige != quiz.Fragen.length - 1) {
        $("#btnAntwort").hide();
        $('h3').append("<p>Insgesamt " + richtige + " von " + (quiz.Fragen.length-1) + " Fragen</br> richtig beantwortet!</p>");
      }
    }
    if (lastFrage) {
      $("#btnAntwort").hide();
      $('h3').append("<p>Insgesamt " + richtige + " von " + quiz.Fragen.length + " Fragen</br> richtig beantwortet!</p>");
      if (richtige == quiz.Fragen.length) {
        document.body.style.backgroundColor = "white";
        $(imgFinal).show();
        audio = document.getElementById("audio");
        audio.play();
      }
    }
    $('#lText').html(loesungS);
    fNr += 1;
    return fBeantwortet = true;
  };

  neueFrage = function() {
    var antw, i, j, len, ref;
    fBeantwortet = false;
    $(imgTrue).hide();
    $(imgFalse).hide();
    $('h2').show();
    $('h3').show();
    $("#btnAntwort").html("Stimmt's?");
    frage = quiz.Fragen[fNr];
    $('h2').html(frage.Kategorie);
    $('h3').html(frage.Frage);
    ref = frage.Antworten;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      antw = ref[i];
      $("#Antwort" + (i + 1)).html(antw);
    }
    return $("#Antworten").show();
  };

  $(function() {
    $('h1').html(quiz.title);
    $(imgTrue).hide();
    $(imgTrue).html("<img src=\"" + quiz.ImgsTF[0] + "\">");
    $(imgFalse).hide();
    $(imgFalse).html("<img src=\"" + quiz.ImgsTF[1] + "\">");
    $(imgFinal).hide();
    $(imgFinal).html("<img src=\"" + quiz.imgFinal + "\">");
    $('body').append("<img src=\"" + quiz.img + "\" style=\"position:absolute;top:10px;right:5%\">");
    $("#Antworten").hide();
    $('h2').html(quiz.title);
    $('h3').html("");
    $("#btnAntwort").html("Weiter zu Frage " + (fNr + 1));
    return $("#btnAntwort").click(function() {
      if (fBeantwortet) {
        return neueFrage();
      } else {
        return checkAntwort();
      }
    });
  });

}).call(this);

//# sourceMappingURL=antolina.js.map
